name: docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Clear pnpm cache
        run: pnpm clear-cache

      - name: Check pnpm version
        run: pnpm --version

      - name: Setup npm
        uses: pnpm/action-setup@v3
        with:
          # choose pnpm version to use
          version: '3'
          # install deps with pnpm
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # choose 
